apiVersion: v1
kind: Service
metadata:
  name: next
spec:
  type: ClusterIP
  selector:
    app: next
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nextfront
spec:
  type: ClusterIP
  selector:
    app: nextfront
  ports:
    - port: 80
      targetPort: 80
