apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: default
spec:
  secretName: wildcard
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.ambassamart.shop'
  dnsNames:
  - '*.ambassamart.shop'
  - ambassamart.shop