apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  secretName: wildcard
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: '*.ambassamart.shop'
  dnsNames:
  - '*.ambassamart.shop'
  - ambassamart.shop