apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rania.midaoui@insat.ucar.tn
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: 5dfcf723-ea7b-4a89-b344-86968954d351
            resourceGroupName: projectrg
            hostedZoneName: ambassamart.shop
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud
            # optional, only required if node pools have more than 1 managed identity assigned
            managedIdentity:
              # client id of the node pool managed identity
              clientID: 52971a4e-47a2-4fb4-bc03-30d5dd247a62