apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ingress-app
spec:
  ingressClassName: nginx
  rules:
  - host: admin.ambassamart.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminfront
            port:
              number: 80
  - host: ambassador.ambassamart.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ambassadorfront
            port:
              number: 80