apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ambassadorapp.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ambassadorfront
                port:
                  number: 4000 
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: adminfront
                port:
                  number: 5200
          - path: /next
            pathType: Prefix
            backend:
              service:
                name: nextfront
                port:
                  number: 3000