apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: 'true'
    # nginx.ingress.kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/issuer: "letsencrypt"
    # certmanager.k8s.io/acme-challenge-type: dns01
  name: ingress-app

spec:
  tls:
    - hosts:
        - admin.ambassamart.shop
        - ambassador.ambassamart.shop
        - checkout.ambassamart.shop
        - '*.ambassamart.shop'
      secretName: wildcard
  rules:
    - host: admin.ambassamart.shop
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: adminfront
              port:
                number: 80
    - host: ambassador.ambassamart.shop
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ambassadorfront
              port:
                number: 80
    - host: checkout.ambassamart.shop
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextfront
              port:
                number: 80