pipeline {

    environment{
      REGISTRY = "raniamidaoui"
      IMAGE_NAME= "admin-app"
      IMAGE_VERSION = "1.0"
      REGISTRY_CRED = 'docker_creds'
      K8S_CONFIG_NAME="kubeconfig"
      K8S_NAMESPACE = 'default'
      K8S_DEPLOYMENT_NAME = "adminfront"
    }

    agent any
    
    stages {


        stage("Build"){
            steps {
                echo "Docker Build"
                script{
                    dockerImg = docker.build("${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}", "Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/react-admin/")
                }
            }
            post{
                success{
                    echo "Build Successful"
                }
                failure{
                    echo "Build Failed"
                }
            }
        }
         
        stage("Push"){
            steps{
                script{
                    docker.withRegistry('', "${REGISTRY_CRED}") {
                        dockerImg.push()
                    }
                }
            }
            post{
                    success{
                        echo "Push Successful"
                    }
                    failure{
                        echo "Push Failed"
                    }
            }
        }

        stage('Deploy') {
            steps {
                script{
                    docker.image('bitnami/kubectl').inside("--entrypoint=''"){
                        withKubeConfig([credentialsId: "$K8S_CONFIG_NAME", namespace: "$K8S_NAMESPACE"]) {
                            sh "kubectl -n \${K8S_NAMESPACE} rollout restart deployment.apps/\${K8S_DEPLOYMENT_NAME}"
                        }
                    }
                }                
            }
        }

    }


    post { 
        always { 
            cleanWs()
        }
    }
}