pipeline {

    environment{
      REGISTRY = "raniamidaoui"
      IMAGE_NAME= "admin-app"
      IMAGE_VERSION = "1.0"
      REGISTRY_CRED = 'docker_creds'
    }

    agent any
    
    stages {


        stage("Build"){
            steps {
                echo "Docker Build"
                script{
                    dockerImg = docker.build("${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}", "./Ambassador_App_Frontend-main/react-admin")
                }
            }
            post{
                success{
                    echo "Build Successful"
                }
                failure{
                    echo "Build Failed"
                }
            }
        }
         
        stage("Push"){
            steps{
                script{
                    docker.withRegistry('', "${REGISTRY_CRED}") {
                        dockerImg.push()
                    }
                }
            }
            post{
                    success{
                        echo "Push Successful"
                    }
                    failure{
                        echo "Push Failed"
                    }
            }
        }

    }


    post { 
        always { 
            cleanWs()
        }
    }
}