apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassadorfront
  labels:
    app: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador
  template:
    metadata:
      labels:
        app: ambassador
    spec:
      containers:
      - name: ambass-app-dev
        image: sadook/ambassador_app
        ports:
        - containerPort: 80
