apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextfront
  labels:
    app: next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: nextfront
        image: raniamidaoui/nextfront
        ports:
        - containerPort: 3000